# Generated by Django 4.1.3 on 2023-04-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cartegory',
                'verbose_name_plural': 'Cartegories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('cartegories', models.ManyToManyField(to='products.cartegory')),
            ],
        ),
    ]
