# Generated by Django 4.1.3 on 2023-04-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cartegories',
            field=models.ManyToManyField(blank=True, to='products.cartegory'),
        ),
    ]
